import { DOCUMENT, NgFor } from '@angular/common';
import { Component, Inject } from '@angular/core';
import { CarouselModule } from 'ngx-bootstrap/carousel';

@Component({
  selector: 'app-principais-pesquisas',
  standalone: true,
  imports: [
    NgFor,
    CarouselModule
  ],
  templateUrl: './principais-pesquisas.component.html',
  styleUrl: './principais-pesquisas.component.css'
})
export class PrincipaisPesquisasComponent {
  itemsPerSlide = 4;
  images = [
    {image: 'assets/images/pesquisas/image1.png', title : 'Ciência no Brand!', shortMessage: 'Nos últimos anos, tem-se observado um aumento significativo no número de pessoas que associam suas pesquisas às marcas. A internet e as redes sociais tornaram as marcas mais acessíveis e interativas, enquanto a proliferação de dispositivos móveis facilita a busca por informações específicas. Além disso, estratégias de marketing digital, como SEO e marketing de conteúdo, ajudam as marcas a serem facilmente encontradas, construindo confiança e autoridade junto ao público. Essa mudança reflete um comportamento de consumo moderno, que valoriza a conveniência e a confiabilidade nas decisões de compra.'},
    {image: 'assets/images/pesquisas/image2.png', title : 'Ciência no Brand!', shortMessage: 'Nos últimos anos, tem-se observado um aumento significativo no número de pessoas que associam suas pesquisas às marcas. A internet e as redes sociais tornaram as marcas mais acessíveis e interativas, enquanto a proliferação de dispositivos móveis facilita a busca por informações específicas. Além disso, estratégias de marketing digital, como SEO e marketing de conteúdo, ajudam as marcas a serem facilmente encontradas, construindo confiança e autoridade junto ao público. Essa mudança reflete um comportamento de consumo moderno, que valoriza a conveniência e a confiabilidade nas decisões de compra.'},
    {image: 'assets/images/pesquisas/image3.png', title : 'Ciência no Brand!', shortMessage: 'Nos últimos anos, tem-se observado um aumento significativo no número de pessoas que associam suas pesquisas às marcas. A internet e as redes sociais tornaram as marcas mais acessíveis e interativas, enquanto a proliferação de dispositivos móveis facilita a busca por informações específicas. Além disso, estratégias de marketing digital, como SEO e marketing de conteúdo, ajudam as marcas a serem facilmente encontradas, construindo confiança e autoridade junto ao público. Essa mudança reflete um comportamento de consumo moderno, que valoriza a conveniência e a confiabilidade nas decisões de compra.'},
    {image: 'assets/images/pesquisas/image4.png', title : 'Ciência no Brand!', shortMessage: 'Nos últimos anos, tem-se observado um aumento significativo no número de pessoas que associam suas pesquisas às marcas. A internet e as redes sociais tornaram as marcas mais acessíveis e interativas, enquanto a proliferação de dispositivos móveis facilita a busca por informações específicas. Além disso, estratégias de marketing digital, como SEO e marketing de conteúdo, ajudam as marcas a serem facilmente encontradas, construindo confiança e autoridade junto ao público. Essa mudança reflete um comportamento de consumo moderno, que valoriza a conveniência e a confiabilidade nas decisões de compra.'},
    {image: 'assets/images/pesquisas/image5.png', title : 'Ciência no Brand!', shortMessage: 'Nos últimos anos, tem-se observado um aumento significativo no número de pessoas que associam suas pesquisas às marcas. A internet e as redes sociais tornaram as marcas mais acessíveis e interativas, enquanto a proliferação de dispositivos móveis facilita a busca por informações específicas. Além disso, estratégias de marketing digital, como SEO e marketing de conteúdo, ajudam as marcas a serem facilmente encontradas, construindo confiança e autoridade junto ao público. Essa mudança reflete um comportamento de consumo moderno, que valoriza a conveniência e a confiabilidade nas decisões de compra.'},
    {image: 'assets/images/pesquisas/image6.png', title : 'Ciência no Brand!', shortMessage: 'Nos últimos anos, tem-se observado um aumento significativo no número de pessoas que associam suas pesquisas às marcas. A internet e as redes sociais tornaram as marcas mais acessíveis e interativas, enquanto a proliferação de dispositivos móveis facilita a busca por informações específicas. Além disso, estratégias de marketing digital, como SEO e marketing de conteúdo, ajudam as marcas a serem facilmente encontradas, construindo confiança e autoridade junto ao público. Essa mudança reflete um comportamento de consumo moderno, que valoriza a conveniência e a confiabilidade nas decisões de compra.'},
    {image: 'assets/images/pesquisas/image7.png', title : 'Ciência no Brand!', shortMessage: 'Nos últimos anos, tem-se observado um aumento significativo no número de pessoas que associam suas pesquisas às marcas. A internet e as redes sociais tornaram as marcas mais acessíveis e interativas, enquanto a proliferação de dispositivos móveis facilita a busca por informações específicas. Além disso, estratégias de marketing digital, como SEO e marketing de conteúdo, ajudam as marcas a serem facilmente encontradas, construindo confiança e autoridade junto ao público. Essa mudança reflete um comportamento de consumo moderno, que valoriza a conveniência e a confiabilidade nas decisões de compra.'},
    {image: 'assets/images/pesquisas/image8.png', title : 'Ciência no Brand!', shortMessage: 'Nos últimos anos, tem-se observado um aumento significativo no número de pessoas que associam suas pesquisas às marcas. A internet e as redes sociais tornaram as marcas mais acessíveis e interativas, enquanto a proliferação de dispositivos móveis facilita a busca por informações específicas. Além disso, estratégias de marketing digital, como SEO e marketing de conteúdo, ajudam as marcas a serem facilmente encontradas, construindo confiança e autoridade junto ao público. Essa mudança reflete um comportamento de consumo moderno, que valoriza a conveniência e a confiabilidade nas decisões de compra.'},
  ];
}
